FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as buils-env
WORKDIR /app

#copy csproj and restore as distinct layer
COPY *.csproj ./
RUN dotnet restore

#copy everything else and build
COPY . ./
RUN dotnet build
RUN dotnet publish -c Release -o out

# build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 as runtime
WORKDIR /app
COPY --from=buils-env /app/out ./
ENTRYPOINT ["dotnet","OrderService.dll"]